### ISSUE TITLE
No Podspec

### ISSUE THREAD

**Issue by segiddins** [nicolaschengdev/WYPopoverController#1]
@nicolaschengdev, the last commit removed the Podspec, making it impossible to do
`pod 'WYPopoverController', :git => 'https://github.com/nicolaschengdev/WYPopoverController'`

**Comment by nicolaschengdev** [comment]
Hi segiddins,

the 'podspec' file was added. You can now use the bleeding edge version of the Pod. Or a specific revision.

**Comment by segiddins** [comment]
Thanks!
