### ISSUE TITLE
Popover flashes if you tried to rotate the device (even if you do not support except one orientation)

### ISSUE THREAD

**Issue by pahmed** [nicolaschengdev/WYPopoverController#12]

**Comment by iGranDav** [comment]
I've experienced the same issue when passing from `UIDeviceOrientationFaceUp` to `UIDeviceOrientationPortrait` you should not listen these notifications. Only `UIInterfaceOrientation` changes.

**Comment by nicolaschengdev** [comment]
Thanks David,
you're right.

It's better to listen `UIApplicationDidChangeStatusBarOrientationNotification` notifications which are posted when the orientation of the application's user interface changes.

**Nicolas**
