### ISSUE TITLE
Showing a UITableViewController as a popover

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [nicolaschengdev/WYPopoverController#127]
Hi,

In my app, there is a UITableViewController. The cell is a custom cell with a button on it. I want to display a popover which is another smaller UITableViewController when that button pressed.

Below is my code,

**TableViewController.m** - The main table view with the custom cell

```
#import "TableViewController.h"
#import "CustomTableViewCell.h"

@interface TableViewController () <UITableViewDataSource, UITableViewDelegate>

@end

@implementation TableViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
}

#pragma mark - UITableViewDataSource
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return 10;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    CustomTableViewCell *cell = (CustomTableViewCell *)[tableView dequeueReusableCellWithIdentifier:@"cell" forIndexPath:indexPath];

    return cell;
}

@end

```

**MiniTableViewController.m** - The smaller table view which is the content view of the popover. Normal cells are used here.

```
#import "MiniTableViewController.h"

@interface MiniTableViewController () <UITableViewDataSource, UITableViewDelegate>

@end

@implementation MiniTableViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
}

#pragma mark - UITableViewDataSource
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return 6;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"minicell" forIndexPath:indexPath];

    cell.textLabel.text = [NSString stringWithFormat:@"%ld", (long)indexPath.row];

    return cell;
}
```

**CustomTableViewCell.m** - The custom table view cell used in the main table view.

```
#import "CustomTableViewCell.h"
#import "MiniTableViewController.h"
#import "WYPopoverController.h"

@interface CustomTableViewCell() <WYPopoverControllerDelegate>

@property (strong, nonatomic) WYPopoverController *popoverController;

@end

@implementation CustomTableViewCell

- (IBAction)popButtonPressed:(UIButton *)sender
{
    self.popoverController = [[WYPopoverController alloc] initWithContentViewController:[MiniTableViewController new]];
    self.popoverController.delegate = self;
    [self.popoverController presentPopoverFromRect:sender.bounds inView:sender permittedArrowDirections:WYPopoverArrowDirectionLeft animated:YES];
}

- (BOOL)popoverControllerShouldDismissPopover:(WYPopoverController *)controller
{
    return YES;
}

- (void)popoverControllerDidDismissPopover:(WYPopoverController *)controller
{
    self.popoverController.delegate = nil;
    self.popoverController = nil;
}
```

When I run this, I get an error at the following line in **MiniTableViewController.m** file.

```
UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"minicell" forIndexPath:indexPath];
```

The error is,
_Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier minicell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'_

But I **do** have specified the identifier for the cell in the storyboard. I don't know why this error is still throwing?

I have uploaded a runnable Xcode project demonstrating my issue here. 
https://www.dropbox.com/s/545m2ki96fddcfj/Popover.zip

If you can take a quick look and tell me what's causing this, I'll really appreciate it.

Thank you.

**Comment by mythodeia** [comment]
@Isuru-Nanayakkara 
according to the documentation in order to use this method:
dequeueReusableCellWithIdentifier ... forIndexPath
you should register a nib or a class.

the reason it works in your "TableViewController" and not in the "MiniTableViewController" is that in the 1st one you are using a CustomTableViewCell. In the 2nd case you are using a simple uitableviewcell.
change it to a custom one or add this line:
[self.tableView registerClass:[UITableViewCell class] forCellReuseIdentifier:@"minicell"];
in your viewDidLoad method in the MiniTableViewController.m file
just tried it and it works fine

**Comment by Isuru-Nanayakkara** [comment]
@mythodeia Hi, thanks for the reply. :) It worked :+1:
