### ISSUE TITLE
Work with InAppSettingsKit?

### ISSUE THREAD

**Issue by horaceho** [nicolaschengdev/WYPopoverController#13]
Anyone pops an `IASKAppSettingsViewController` [InAppSettingsKit](https://github.com/futuretap/InAppSettingsKit) inside `WYPopoverController` successfully? I following the `UINavigationController` sample:

```
    UINavigationController* navigationController = [[UINavigationController alloc] initWithRootViewController:self.infoViewController];
    UIViewController* contentViewController = navigationController;

    WYPopoverController* popoverController = [[WYPopoverController alloc] initWithContentViewController:contentViewController];
    popoverController.delegate = self;
    [popoverController presentPopoverFromRect:self.infoButton.bounds
                                       inView:self.infoButton
                     permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES];

```

but second-level `IASKAppSettingsViewController`s are not pushed as expected.

**Comment by nicolaschengdev** [comment]
Hi !

Your `WYPopoverController` is deallocated while it is still visible. 

`WYPopoverController` works like `UIPopoverController` and both of them should always be held in an instance variable. It is a good practice to create a strong property for it.

**Nicolas**

**Comment by horaceho** [comment]
Thank you!
