### ISSUE TITLE
Using a storyboard identifier - drops UINavigationController

### ISSUE THREAD

**Issue by tatejones** [nicolaschengdev/WYPopoverController#14]
I have the following code.

UINavigationController _navigationController = [[UINavigationController alloc] initWithRootViewController: [self.storyboard instantiateViewControllerWithIdentifier:name]];
UIViewController *contentViewController = navigationController;
WYPopoverController_ popoverController = [[WYPopoverController alloc] initWithContentViewController:contentViewController];
popoverController.delegate = self;
[popoverController presentPopoverFromRect:view.bounds inView:view permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES];

The controller loaded via the storyboard called is a UITableViewController.  The UITableViewController is loaded, however any future calls to push additional view controllers within this wrapped controller results in the following error.

Exception - Could not find a navigation controller for segue 'selectCategory'. Push segues can only be used when the source controller is managed by an instance of UINavigationController.

It is like the controller within the popover has dropped the UINavigationController.

**Comment by nicolaschengdev** [comment]
Hi tatejones.

I have not been able to reproduce your issue.
- I loaded an `UITableViewController` named _StadiumList_ via storyboard
- I created manually an `UINavigationController` and I defined _StadiumList_ instance as root view controller 
- I presented the whole with a popover

And when I select any tableCell it triggers a push segue to another view controller.

Without errors.

Your `popoverController` is certainly deallocated while it is still visible.
Try to hold it into an ivar.

My code :

**WYViewController.h**

``` objective-c
#import <UIKit/UIKit.h>

@interface WYViewController : UIViewController

- (IBAction)buttonTap:(id)sender;

@end

```

**WYViewController.m**

``` objective-c
#import "WYViewController.h"
#import "WYPopoverController.h"

@interface WYViewController () <WYPopoverControllerDelegate>
{
    WYPopoverController* popoverController;
}

@end

@implementation WYViewController

- (IBAction)buttonTap:(id)sender
{
    UIView* view = (UIView *)sender;

    UINavigationController* contentViewController = [[UINavigationController alloc] initWithRootViewController:[self.storyboard instantiateViewControllerWithIdentifier:@"StadiumList"]];

    popoverController = [[WYPopoverController alloc] initWithContentViewController:contentViewController];
    popoverController.delegate = self;

    [popoverController presentPopoverFromRect:view.bounds inView:view permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES];
}

- (BOOL)popoverControllerShouldDismiss:(WYPopoverController *)aPopoverController
{
    return YES;
}

@end

```
