### ISSUE TITLE
Unable to dismiss popover...from popover.

### ISSUE THREAD

**Issue by 128keaton** [nicolaschengdev/WYPopoverController#142]
Hey everyone, I am having an odd issue thats easy to solve, I probably just can't see it. Basically, I am trying to programmatically dismiss the popover from the popover, for which I haven't had success with.
Here is the code I am trying (hooked up to a button in the popover):
[self.delegate dismissPopoverAnimated:YES];
where delegate is set to:
selectionViewController.delegate = (MasterViewController*) self.view.window.rootViewController;
MasterViewController is the view controller from which I am instigating the popover. Any suggestions?

**Comment by gitsumakwel** [comment]
Hello keaton. I was trying to dismiss the popover myself. I just want to share what i got so far.

1: WYPopoverController.h - add on top
    @class WYPopoverBackgroundView;
2: WYPopoverController.h - find 
    interface WYPopoverBackgroundView
3: add 
    @property(nonatomic, assign) id&lt;WYPopoverBackgroundViewDelegate&gt; delegate;
4: add this protocol
    #pragma mark
    #pragma mark - WYPopoverBackgroundViewDelegate
    @protocol WYPopoverBackgroundViewDelegate <NSObject>
    @optional
    - (void)popoverBackgroundViewDidTouchOutside:(WYPopoverBackgroundView *)backgroundView;
    @end

5: WYPopoverController.m - find the previous protocol you added and //comment
//    #pragma mark
//    #pragma mark - WYPopoverBackgroundViewDelegate
//    @protocol WYPopoverBackgroundViewDelegate <NSObject>
//    @optional
//   - (void)popoverBackgroundViewDidTouchOutside:(WYPopoverBackgroundView *)backgroundView;
//    @end

6: WYPopoverController.m - find and //comment
    // @property(nonatomic, assign) id&lt;WYPopoverBackgroundViewDelegate&gt; delegate;

a) Then on your custom popover View
b) Place a button - call Dismiss
c) Button - make a connection to the controller name: dismissButtonAction
d) Inside -(IBAction)dissmissButtonAction:(id)sender ,enter this code
    WYPopoverBackgroundView *backgroundView =[[self.view.window subviews] lastObject];
    backgroundView.delegate popoverBackgroundViewDidTouchOutside:backgroundView];

I hope they will see this and merge this procedure.

**Comment by 128keaton** [comment]
@gitsumakwel so this works? I will experiment later today, thanks for your input.

**Comment by gitsumakwel** [comment]
yes it works completely.

its for custom popover.
you can do what i just  did to dismiss the custom popover by pressing a
button.

**Comment by 128keaton** [comment]
@gitsumakwel thanks! This works well, going to close, hopefully it helps other people.

**Comment by 128keaton** [comment]
@gitsumakwel tried adding: 
@property(nonatomic, assign) id<WYPopoverBackgroundViewDelegate> delegate;
but it just errors

**Comment by rsanchezsaez** [comment]
Please, check if this is an issue on [sammcewan's fork](https://github.com/sammcewan/WYPopoverController) (which is actively maintained), and report it there if it is. Thanks.

**Comment by Shjv4** [comment]
This is how I dismiss popUpVC: 

in ParentViewController.h, declare an public method for dismiss popup view controller
- (void)dismissPopUpViewController;

in ParentViewController.m 
- (void)dismissPopUpViewController {
  [self.popupVC dismissPopoverAnimated:YES];
  }

PopUpSpotViewController *popupSpotVC       = [[PopUpSpotViewController alloc] initWithNibName:@"PopUpSpotViewController" bundle:nil];
    self.popupVC                               = [[WYPopoverController alloc] initWithContentViewController:popupSpotVC];
    self.popupVC.delegate                      = self;
    self.popupVC.wantsDefaultContentAppearance = YES;
    popupSpotVC.preferredContentSize           = CGSizeMake(300, 110);
    popupSpotVC.parentVC = self;
    [self.popupVC presentPopoverFromRect:view.bounds inView:view permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES];

in PopUpSpotViewController.h: 

@property (strong, nonatomic) ParentViewController *parentVC;

and last, in PopUpSpotViewController.m 
- (IBAction)buttonDismissPopUpViewPressed:(id)sender {
  NSLog(@"--- Call for dismiss this pop up view ---");
  [self.parentVC dismissPopUpViewController];
  }

**Comment by 98chimp** [comment]
@gitsumakwel: worked like a charm for me. thx for sharing

**Comment by 128keaton** [comment]
Here is how I do it:

`UIWindow *mainWindow = [[[UIApplication sharedApplication] windows] objectAtIndex:0]; for (UIView *view in mainWindow.subviews) { if (view.class == [WYPopoverOverlayView class]) { [(WYPopoverOverlayView *)view touchesBegan:nil withEvent:nil]; } NSLog(@"Subviews %@", mainWindow.subviews); }`
