### ISSUE TITLE
viewDidAppear is called twice in some case

### ISSUE THREAD

**Issue by pebble8888** [nicolaschengdev/WYPopoverController#143]
Sample project for iPad is here.
https://github.com/pebble8888/PopoverSample

**Comment by pebble8888** [comment]
I fixed the problem in my branch.
https://github.com/pebble8888/WYPopoverController

Why does it call view{ Will | Did }{ Appear | Didappear } expressly so far?

**Comment by rsanchezsaez** [comment]
Please, check if this is an issue on [sammcewan's fork](https://github.com/sammcewan/WYPopoverController) (which is actively maintained). If it is, report it there and/or submit a pull request to that fork. Thanks.

**Comment by pebble8888** [comment]
Thank you for your reply. I get it.
