### ISSUE TITLE
Is iOS 5.1 supported - setDrawsAsynchronously?

### ISSUE THREAD

**Issue by tatejones** [nicolaschengdev/WYPopoverController#16]
I appreciate your prompt support.  Great for overtime.

I have just upgrade to 0.1.2 for issue #15.  Now the following exception is occurring.

-[CALayer setDrawsAsynchronously:]: unrecognized selector sent to instance 0xa416480
 **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CALayer setDrawsAsynchronously:]: unrecognized selector sent to instance 0xa416480'

self.layer.drawsAsynchronously = YES;

iOS 6 only now?  

Cheers

**Comment by nicolaschengdev** [comment]
Thanks tatejones for your reports.

It helps me to improve `WYPopooverController`.

I have just commited on master a fix for this issue. In hope it will be sufficient.

**Nicolas**
