### ISSUE TITLE
Why is my arrow rounded?

### ISSUE THREAD

**Issue by Ricardo1980** [nicolaschengdev/WYPopoverController#160]
Hello!

See attached screen. I'm looking for a flat style.
I only use this line:
[[WYPopoverBackgroundView appearance] setOuterCornerRadius:0];

As expected, the corners are flat, but the arrow is rounded. How can I remove the round in the arrow?

Thanks.

![captura de pantalla 2014-12-23 a las 17 50 34](https://cloud.githubusercontent.com/assets/738681/5540632/084e86ca-8ace-11e4-8e06-02f69e12eccd.png)

**Comment by tkach** [comment]
Hi, @Ricardo1980 , to make your arrow flat you need to set this flag to 0.
[[WYPopoverBackgroundView appearance] setUsesRoundedArrow:0];

Hope it helps.
BTW, this lib is now maintained by another person, please look at this fork
https://github.com/sammcewan/WYPopoverController

**Comment by Ricardo1980** [comment]
Thanks a lot @tkach
