### ISSUE TITLE
iOS7 Support?

### ISSUE THREAD

**Issue by CrEaK** [nicolaschengdev/WYPopoverController#17]
The WYPopoverController has graphical glichtes in iOS7. Is it planned to Support iOS7 as well?

Thanks for your Help!

**Comment by nicolaschengdev** [comment]
Hi CrEaK. Yes it is planned to support iOS 7 in the next release (0.1.3).
With a white theme as default for iOS 7.

**Nicolas**

**Comment by nicolaschengdev** [comment]
Work in progress...

![wypopover_ios7](https://f.cloud.github.com/assets/2202583/1136353/dc38fe84-1c3e-11e3-8766-90cddb5f1690.jpg)
