### ISSUE TITLE
can't set Appearance on WYPopoverController

### ISSUE THREAD

**Issue by vatsal1992** [nicolaschengdev/WYPopoverController#171]
i've seen the both example code and demo project. if it is possible, can you update your demo project with Appearance Code? because i use example code of Appearance but nothing change in popover. so, where to add Appearance in popoverController. (i'm new on iOS)

**Comment by gabinogueira** [comment]
Hi,
What I did for change the appearance was this:

```
WYPopoverTheme *theme = settingsPopoverController.theme;
theme.fillTopColor = [UIColor redColor];
theme.fillBottomColor = [UIColor redColor];
theme.tintColor = [UIColor redColor];
theme.outerCornerRadius = 50;
[settingsPopoverController setTheme:theme];
```

In the WYPopoverTheme object, you can change everything you want, like the methods themeForIOS6 and themeForIOS7 of the WYPopoverController class.
