### ISSUE TITLE
Wrong overlay position when showing popover from view controller that was presented modally

### ISSUE THREAD

**Issue by shkutkov** [nicolaschengdev/WYPopoverController#19]
In case of showing popover from view controller that was presented modally, overlay position is wrong.

For test purposes I've changed WYPOPOVER_DEFAULT_OVERLAY_COLOR to red color.

<img src="https://f.cloud.github.com/assets/426913/1138104/c24ca3b0-1c6e-11e3-8548-ed2d335d7a13.png" width="50%">

There is a gap (white stripe) between status bar and overlay.

**Comment by nicolaschengdev** [comment]
Overlay position has been fixed in the a227bdd357eaab00f08397c6cc8d84523d981afe commit.
