### ISSUE TITLE
Supporting UINavigationController

### ISSUE THREAD

**Issue by tatejones** [nicolaschengdev/WYPopoverController#2]
When attempting to add a UINavigationController to the popover it will appear, however any push of a viewController ( [self performSegueWithIdentifier:@"segueName" sender:self]) will fail to do anything.

Any ideas?

Cheers

**Comment by nicolaschengdev** [comment]
Hi tatejones,

UINavigationController is supported. However UIStoryboardSegue is not.
The DEMO app implements a popover which is used with an UINavigationController.
I am watching how to add segue objects support.

Nicolas

**Comment by tatejones** [comment]
Cheers.  I have been testing FPPopover, however it seems move complicated than it needs to be and lack UI customisation.  It does support UINavigation from a segue.

**Comment by nicolaschengdev** [comment]
Hi tatejones,

I just added UIStoryboardSegue support to WYPopoverController. And a 'DemoSegue' app showing how to use it.

Nicolas

**Comment by Gman9855** [comment]
Hi nicolas, 

In your demo you are using static cells....  when i try using multiple view controllers within a nav controller and with dynamic cells, when i segue from within the popover it goes to a fullscreen view and gets rid of the popover...  any suggestions?  Thanks!

**Comment by Gman9855** [comment]
never mind, got it working!
