### ISSUE TITLE
 'contentSizeForViewInPopover' is deprecated in iOS 7

### ISSUE THREAD

**Issue by zetachang** [nicolaschengdev/WYPopoverController#20]
Hi, 

The master works pretty fine on iOS 7 :+1: 

But there are still warnings popped out suggesting using `UIViewController.preferredContentSize` instead. I am thinking of a possible workaround which will check if the view controller respond to `preferredContentSize` first. If not, then fallback to use `contentSizeForViewInPopover`.

**Comment by nicolaschengdev** [comment]
Hi zetachang,

thanks for your contribution !

**Nicolas**
