### ISSUE TITLE
Minimum requirement of iOS 7.0

### ISSUE THREAD

**Issue by shkutkov** [nicolaschengdev/WYPopoverController#25]
It seems that now we cannot use WYPopoverControl on iOS 6 via CocoaPods, because of this line:

`s.ios.deployment_target = '7.0'`

Is it mistake?

**Comment by nicolaschengdev** [comment]
Hi shutkov,

there is no mistake.

You can declare in your PodFile that your target platform use ios 7, for example (from one of my projects) : 

```
platform :ios, '7.0'
pod 'JSONKit',                 '~> 1.4'
pod 'Reachability',            '~> 3.1.1'
pod 'GPUImage',                '~> 0.1.0'
pod 'MBProgressHUD',           '~> 0.7'
pod 'iVersion',                '~> 1.10.6'
pod 'AFNetworking',            '~> 1.3.1'
pod 'UIView+EasingFunctions',  '~> 0.0.1'
pod 'WYPopoverController',     '~> 0.1.3'
```

And set the deployment target of your project to iOS 6.1.

**Nicolas**
