### ISSUE TITLE
Popover is not animated when changing popoverContentSize property

### ISSUE THREAD

**Issue by nicolaschengdev** [nicolaschengdev/WYPopoverController#26]
Popover is not animated when changing `popoverContentSize` property.

**Comment by jdewind** [comment]
+1 This would be a really useful feature.

**Comment by jhersh** [comment]
I have a standard nav controller in a `WYPopoverController` and I can't seem to change the popover's size at all after it's been presented. My view controllers implement `preferredContentSize` and I've also tried assigning to the `popoverContentSize` property. 

Any suggestions here?
