### ISSUE TITLE
WYPopoverController crashes if areas array is empty

### ISSUE THREAD

**Issue by bizz84** [nicolaschengdev/WYPopoverController#27]
Crashes on this line:

arrowDirection = ((WYPopoverArea*)[areas objectAtIndex:0]).arrowDirection;

This happens for me when I set the popoverContentSize

Also, ideally the ([areas count] > 1) check should be extended.

**Comment by nicolaschengdev** [comment]
I am not yet satisfied with this method : 

``` objective-c
- (WYPopoverArrowDirection)arrowDirectionForRect:(CGRect)aRect
                                          inView:(UIView*)aView
                                     contentSize:(CGSize)contentSize
                                     arrowHeight:(CGFloat)arrowHeight
                        permittedArrowDirections:(WYPopoverArrowDirection)arrowDirections;
```

But for now it works. Need more tests and situations.

**Nicolas**
