### ISSUE TITLE
Appereance proxy

### ISSUE THREAD

**Issue by mbigatti** [nicolaschengdev/WYPopoverController#3]
Hi. I was trying to customize the popover appearance but it seems that the proxies are implemented in an internal view not exposed with public API. I'm missing something?

regards,
MB

**Comment by nicolaschengdev** [comment]
Hi MB!

What did you try to customize ?

Show me few lines of your code where you attempt to use WYPopoverController please.

A simple example :

WYPopoverBackgroundView\* appearance = [WYPopoverBackgroundView appearance];
[appearance setBorderWidth:8];
[appearance setArrowHeight:10];
[appearance setArrowBase:20];
...

For wait, 
WYPopoverBackgroundView extends UIView which is compliant with UIAppearance.
This internal view is not designed like UIPopoverBackgroundView which needs images.

With WYPopoverController, popovers are drawn programmatically. 
So, you don't need to extend WYPopoverBackgroundView if it is not necessary.

You can fork WYPopoverController if you want to evolve it.

Nicolas

**Comment by mbigatti** [comment]
sorry, now I got it.

**Comment by nicolaschengdev** [comment]
No worry !
