### ISSUE TITLE
Value stored to 'reducedOuterCornerRadius' during its initialization is never read

### ISSUE THREAD

**Issue by JulesMoorhouse** [nicolaschengdev/WYPopoverController#31]
Hi,

I'm getting the following Xcode 5 analyser warning…

/snip/Classes/WYPopoverController/WYPopoverController.m:951:17: Value stored to 'reducedOuterCornerRadius' during its initialization is never read

Jules.

**Comment by nicolaschengdev** [comment]
Hi,

which version of Xcode do you use ?

I have installed the latest Xcode 5 (from App Store) and I haven't this error.
Can you retry with the latest version of Xcode 5 please. And reopen this issue if it need.

**Nicolas**

**Comment by JulesMoorhouse** [comment]
Yeah I've just updated beta 6 to the App Store version and got that warning

Jules

**Comment by nicolaschengdev** [comment]
My version of _Xcode 5_ is `5A1413`.
My version of _MacOSX_ is `10.8.5`.

And I cannot reproduce this issue using static analyzer. See screenshot.

![capture decran 2013-09-19 a 16 51 33](https://f.cloud.github.com/assets/2202583/1173629/0ad4f346-213b-11e3-92bd-784a94be935a.png)

**Comment by shkutkov** [comment]
Hi Jules,

Are you using the latest version of WYPopoverController - 0.1.4? I had the same issue with 0.1.3 and now it's gone.

**Comment by JulesMoorhouse** [comment]
Yes this is now fixed with the current code.

**Comment by nicolaschengdev** [comment]
Thanks @shkutkov for your comment !
Happy coding @Jules2010 !
