### ISSUE TITLE
iOS7 support

### ISSUE THREAD

**Issue by iGranDav** [nicolaschengdev/WYPopoverController#32]
The popover does not showing well on iOS7.

It's totally shrinked.

Thanks in advance.

**Comment by nicolaschengdev** [comment]
Hi,

could you provide me a screenshot please. And a sample code please.

Thanks.

**Comment by iGranDav** [comment]
Hi,

I've just tested on your demo project on **iOS 7** and it works. Here is why : you define a content size for your view in popover via `contentSizeForViewInPopover` property. 

In **iOS 6** when you don't define any size the embedded controller take the maximum screen size : now it's totally shrinked (cf. screenshot)
![capture decran du simulateur ios 23 sept 2013 17 11 18](https://f.cloud.github.com/assets/75418/1192400/0c5457d2-2462-11e3-960b-2a7ae66072ef.png)

So there is a workaround from now :-) thanks for that.

**Comment by iGranDav** [comment]
I was running an old version ( **1.2.0** ), last stable ( **1.4.0** ) fixed that... Sorry for inconvenience.

Thanks for support !

**Comment by nicolaschengdev** [comment]
Never mind.
