### ISSUE TITLE
NSStringFromOrientation and GetStatusBarHeight should be marked as static

### ISSUE THREAD

**Issue by Timac** [nicolaschengdev/WYPopoverController#34]
The methods
NSString\* NSStringFromOrientation(NSInteger orientation)
and
CGFloat GetStatusBarHeight()

generate a warning "No previous prototype for function" because the 'static' keyword is missing.

To fix these warnings, the static keyword needs to be added:
static NSString\* NSStringFromOrientation(NSInteger orientation)
static CGFloat GetStatusBarHeight()

**Comment by nicolaschengdev** [comment]
thanks !

**Comment by inPhilly** [comment]
I get a warning in my compiler "unused function 'NSStringFromOrientation'"

**Comment by osrl** [comment]
i get the same warning too with @mommyme
