### ISSUE TITLE
Using UINavigationController as ContentViewController

### ISSUE THREAD

**Issue by leoahkun** [nicolaschengdev/WYPopoverController#37]
This doesn't seem to work for me.

CCRootViewController *ccrvc = [[CCRootViewController alloc] init];
    UINavigationController *navController = [[UINavigationController alloc] initWithRootViewController:ccrvc];
    self.popoverController = [[WYPopoverController alloc] initWithContentViewController:navController];
    self.popoverController.delegate = self;
    [self.popoverController presentPopoverFromRect:self.bounds inView:self permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES];

**Comment by nicolaschengdev** [comment]
Hi Leonard,

with which version of _WYPopoverController_, are you experiencing your trouble ?
Your application crashes ? The popover appears but content is blank ?

Did you follow examples presented in demos ?

**Nicolas**

**Comment by leoahkun** [comment]
The screen dimmed with no popup. I've managed to solve the problem though setting the preferredContentSize.

thanks

**Comment by nicolaschengdev** [comment]
Great ! 

The last stable release (0.1.4) fixes this bug when `preferredContentSize` is not setted using iOS7.
