### ISSUE TITLE
iOS7 content size

### ISSUE THREAD

**Issue by dwery** [nicolaschengdev/WYPopoverController#38]
It seems there's some extra space between the bottom border and the contentView
with iOS7. The same code works nicely on iOS6.

preferredContentSize is used with iOS7 and contentSizeForViewInPopover on iOS6

**Comment by nicolaschengdev** [comment]
Hi,

The following show you an example for iO6 and iO7. I made two screenshots. And it doesn't seem to have any extra space between the bottom border and the content view of the popover.

**CODE**

``` objective-c
WYPopoverBackgroundView* popoverAppearance = [WYPopoverBackgroundView appearance];
[popoverAppearance setTintColor:[UIColor whiteColor]];
[popoverAppearance setFillBottomColor:[UIColor colorWithWhite:0.75 alpha:1]];
[popoverAppearance setOuterStrokeColor:[UIColor colorWithWhite:0.5 alpha:1]];
[popoverAppearance setInnerStrokeColor:[UIColor colorWithWhite:0.5 alpha:1]];
[popoverAppearance setOuterCornerRadius:8];
[popoverAppearance setMinOuterCornerRadius:8];

[popoverAppearance setOuterShadowBlurRadius:6];
[popoverAppearance setOuterShadowColor:[UIColor colorWithWhite:0 alpha:0.65]];
[popoverAppearance setOuterShadowOffset:CGSizeMake(0, 2)];

[popoverAppearance setGlossShadowColor:[UIColor lightGrayColor]];
[popoverAppearance setGlossShadowOffset:CGSizeMake(0, 1)];

[popoverAppearance setBorderWidth:5];
[popoverAppearance setArrowHeight:20];
[popoverAppearance setArrowBase:42];

[popoverAppearance setInnerCornerRadius:4];
[popoverAppearance setInnerShadowBlurRadius:3];
[popoverAppearance setInnerShadowColor:[UIColor colorWithWhite:0 alpha:0.75]];
[popoverAppearance setInnerShadowOffset:CGSizeMake(0, 1)];

[popoverAppearance setViewContentInsets:UIEdgeInsetsMake(3, 0, 0, 0)];

UINavigationBar* navBarAppearance = [UINavigationBar appearanceWhenContainedIn:[WYPopoverBackgroundView class], [UINavigationController class], nil];
[navBarAppearance setTitleTextAttributes:@{
               UITextAttributeTextColor : [UIColor darkGrayColor],
   UITextAttributeTextShadowColor: [UIColor whiteColor],
  UITextAttributeTextShadowOffset: [NSValue valueWithUIOffset:UIOffsetMake(0, -1)]
}];
```

**SCREENSHOTS**

![screenshot_compare_ios6-7](https://f.cloud.github.com/assets/2202583/1250518/2b7165f2-2afb-11e3-9392-03facd121c7b.png)

**Comment by dwery** [comment]
I'll check again and make a screenshot if the problem persists, thanks

**Comment by dwery** [comment]
Here's my code:

```
    UIViewController *vc = [[UIViewController alloc] init];

    vc.view = [UIDatePicker alloc] init];
    vc.title = @"Data";

    self.pop = [[WYPopoverController alloc] initWithContentViewController:[[UINavigationController alloc] initWithRootViewController:vc]];

    if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"7.0")) {
        vc.preferredContentSize = vc.view.bounds.size;
    } else {
        vc.contentSizeForViewInPopover = vc.view.bounds.size;
    }

    vc.navigationItem.rightBarButtonItem = ...;

    [_pop present.... ];
```

**Comment by nicolaschengdev** [comment]
Hi dwery,

here my code : 

``` objective-c
UIViewController *vc = [[UIViewController alloc] init];
vc.view = [[UIDatePicker alloc] init];
vc.title = @"Data";

datePopoverController = [[WYPopoverController alloc] initWithContentViewController:[[UINavigationController alloc] initWithRootViewController:vc]];

CGSize viewSize = vc.view.bounds.size;

NSLog(@"viewSize = %@", NSStringFromCGSize(viewSize)); // ---> height is 216 instead of 162

if ([vc respondsToSelector:@selector(setPreferredContentSize:)]) {
    vc.preferredContentSize = viewSize;
}
else {
    vc.contentSizeForViewInPopover = viewSize;
}

[datePopoverController presentPopoverFromRect:btn.bounds inView:btn permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES];
```

And like you can see with `NSLog`, when you trace the height of `UIDatePicker`it gives _216_ instead of _162_.

The height _162_ is the real height of an `UIDatePicker` with iOS7.

It is why you have an extra spacing.

It's not an issue coming from `WYPopooverController` but from the implementation of `UIDatePicker` with the iOS SDK 7.0.

Cheers

**Comment by dwery** [comment]
Ouch! Thank you

**Comment by dwery** [comment]
Setting edgesForExtendedLayout = UIRectEdgeNone on the controller solved the issue.

**Comment by nicolaschengdev** [comment]
The commit [6fffc5e8ec](https://github.com/nicolaschengdev/WYPopoverController/commit/6fffc5e8eca14f2f59ef599626fac0915df6b67a) solves this.

**Comment by dwery** [comment]
why the swizzling? Isn't setting it on the controller that gets added to the popover enough?

**Comment by nicolaschengdev** [comment]
Because I try to reproduce the default behaviors of `UIPopoverController`.
One of these behaviors is to automatically set `edgesForExtendedLayout` to `UIRectEdgeNone` on each `UIViewController` embed in an `UINavigationController`.

**Comment by dwery** [comment]
I wonder if they just traverse the tree or have some special hook/delegate

**Comment by nicolaschengdev** [comment]
I don't know how they do their stuff.
Tell me if you find a better way in order to accomplish that.

Cheers

**Nicolas**

**Comment by dwery** [comment]
I guess they have some hidden interface.

 Probably the cleanest way would be to have `WYNavigationController` as a subclass of `UINavigationController`. Then `pushViewController:animated:` could be modified to set the edges.

Pro: cleaner interface
Con: the user has to be instructed to use the new `WYNavigationController`

**Comment by nicolaschengdev** [comment]
My thoughts : It will be very annoying if we have to use a subclass of `UINavigationController`.

I will attempt a try with KVO in order to detect new pushed view controllers into a navigation bar controller.

**Nicolas**
