### ISSUE TITLE
Popover never fadeout

### ISSUE THREAD

**Issue by mrcrow** [nicolaschengdev/WYPopoverController#4]
For WYPopoverController.m, I think it is better to change the codes in the if statements from line 1395 to the following:

 [UIView animateWithDuration:0.15 animations:^{
            overlayView.alpha = 0;
        } completion:^(BOOL finished) {
            completionBlock(YES);
            [viewController viewWillDisappear:YES];
        }];

**Comment by nicolaschengdev** [comment]
Thanks mrcrow !

**Comment by mrcrow** [comment]
You're welcome!
