### ISSUE TITLE
Usage as custom dialog popup?

### ISSUE THREAD

**Issue by scastria** [nicolaschengdev/WYPopoverController#41]
Whenever I needed a custom modal popup dialog, I would always customize UIAlertView.  This leads to trouble since it is not supported and Apple always changes the innerworkings of UIAlertView causing my customizations to break with every iOS release.  Therefore, I started looking at thirdparty popover controllers (to gain iPhone support) and found this one.  It looks and works great.  However, when I want to present it, I must specify some barbutton or view rect to anchor it to.  In order to use this popover controller as more of a general purpose custom dialog popup, it would be nice if there was a new WYPopoverArrowDirection.None and the ability to show it without referencing some anchor point.  The None arrow direction would mean do not show an arrow AND center the dialog on the screen.  I can achieve the hidden arrow by setting the arrowHeight = 0, but I can't find an easy way to just center the popover on the screen.  Could this enhancement be added?  It sounds easy.

**Comment by nicolaschengdev** [comment]
Hi,

good idea. You have just commited so I can stop to work on this enhancement.

**Nicolas**
