### ISSUE TITLE
Visual glitch when borderWidth property set to 0

### ISSUE THREAD

**Issue by bizz84** [nicolaschengdev/WYPopoverController#44]
Setting the borderWidth property to 0 results in a visual glitch at the bottom of the popover. 
![wypopover](https://f.cloud.github.com/assets/153167/1341663/761c7c5e-364f-11e3-94c8-91596c5c4c1c.jpg)

[[WYPopoverBackgroundView appearance] setBorderWidth:0]

Ideally if outerCornerRadius > 0 and borderWidth == 0, the outerCornerRadius is used in the bottom of the popover so that a rounded corner is possible.

**Comment by nicolaschengdev** [comment]
Hi Andrea,

which release of `WYPopoverController`is used ?

Because it seems that it's already handled in release 0.1.6, _WyPopoverController.m_ line 1615 : 

``` objective-c
if (containerView.borderWidth == 0)
{
    viewController.view.layer.cornerRadius = containerView.outerCornerRadius;
}
```

Could you try with 0.1.6 release please ?

**Nicolas**

**Comment by bizz84** [comment]
I've tested with 0.1.6 and the problem persists.
It can be seen in the image attached that the bottom corners are indeed rounded, but some other view's bounds are overlaid and still square.

This is my setup:

```
WYPopoverBackgroundView* popoverAppearance = [WYPopoverBackgroundView appearance];

[popoverAppearance setOuterCornerRadius:8];
[popoverAppearance setOuterShadowBlurRadius:4];
[popoverAppearance setOuterShadowColor:[SUStyle style].colorStrokeDarker];
[popoverAppearance setOuterShadowOffset:CGSizeMake(0, 1)];

[popoverAppearance setGlossShadowColor:[UIColor clearColor]];
[popoverAppearance setGlossShadowOffset:CGSizeMake(0, 0)];

[popoverAppearance setBorderWidth:0]; // Breaks
[popoverAppearance setArrowHeight:12];
[popoverAppearance setArrowBase:20];

[popoverAppearance setInnerCornerRadius:4];
[popoverAppearance setInnerShadowBlurRadius:0];
[popoverAppearance setInnerShadowColor:[UIColor clearColor]];
[popoverAppearance setInnerShadowOffset:CGSizeMake(0, 0)];

[popoverAppearance setFillTopColor:uniformColor];
[popoverAppearance setFillBottomColor:uniformColor];
[popoverAppearance setOuterStrokeColor:uniformColor];
[popoverAppearance setInnerStrokeColor:uniformColor];
```

**Comment by fukemy** [comment]
which class import to include WYPopoverBackgroundView?
