### ISSUE TITLE
never display after add chartboost

### ISSUE THREAD

**Issue by fdddf** [nicolaschengdev/WYPopoverController#47]
After I integrated chartboost's Ad, the popover view can not be shown up.

**Comment by nicolaschengdev** [comment]
I don't know what is Chartboost's Ad and how it works.
If you can tell me how they do their stuff then I will search a solution.

**Nicolas**

**Comment by fdddf** [comment]
@nicolaschengdev 

``` obj-c
Chartboost *cb = [Chartboost sharedChartboost];
    cb.appId = kChartboostAdID;
    cb.appSignature = kChartboostAdSign;

    [cb startSession];
    [cb showInterstitial];
```

That's the code to show ad, likes a popover upon the window layer.
I can not find the source code except the header, 
And this link https://help.chartboost.com/getting-started is their documents. 

And I debuged code with PonyDebugger, 
The WYPopover's background view and overlayview is hidden, alpha is 0, and frame is zero.

Thanks for your help.

**Comment by nicolaschengdev** [comment]
Thanks for your contribution !

**Comment by vuluu** [comment]
sorry! I do not know anywhere to post my question about  WYPopoverController so I decided do it here.  help me to hide done button and change the color text to white or any color, when I set appearance color to black the title is black too.

**Comment by nicolaschengdev** [comment]
Hi,

if you are using an UINavigationController into your popover then try to customize navigation bar like this exemple : 

``` objective-c
UINavigationBar *navBarAppearance = [UINavigationBar appearanceWhenContainedIn:[WYPopoverBackgroundView class], [UINavigationController class], nil];
[navBarAppearance setTitleTextAttributes:@{
    UITextAttributeTextColor : [UIColor darkGrayColor],
    UITextAttributeTextShadowColor: [UIColor clearColor],
    UITextAttributeTextShadowOffset: [NSValue valueWithUIOffset:UIOffsetMake(0, 0)]
}];
```

Which "done" is involved ?
A screenshot and few lines of code could be easier for me in order to help you.

My guess is you are not using _chartboost_, right ?
Open a new issue if I am right please.

Because this issue about _chartboost_ was resolved.

**Comment by vuluu** [comment]
yes, I do it. Help me solve problem in https://github.com/nicolaschengdev/WYPopoverController/issues/49
