### ISSUE TITLE
Hide "done" button and show title of WYPopover

### ISSUE THREAD

**Issue by vuluu** [nicolaschengdev/WYPopoverController#49]
I found problem when i change the appearance color to black  the title is black color too, how to change title color to other color.  Help me to hide the blue Done button. Can I expand the area in the botton of WYPpover? and add other button in there place
here is image from simulator and some code
http://postimg.org/image/9qpr6cand/

**Comment by nicolaschengdev** [comment]
In order to hide the "Done" button, remove this line : 

``` objective-c
[notiTable.navigationItem setRightBarButtonItem:[[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:self action:@selector(done:)]];
```

In your code, `NotificationTable` is a subclass of UINavigationController ? 

If yes then try the following : 

``` objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    WYPopoverBackgroundView *popoverAppearance = [WYPopoverBackgroundView appearance];
    [popoverAppearance setFillTopColor:[UIColor blackColor]];

    UINavigationBar *navBarAppearance = [UINavigationBar appearanceWhenContainedIn:[WYPopoverBackgroundView class], [NotificationTable class], nil];
    [navBarAppearance setTitleTextAttributes:@{
                   UITextAttributeTextColor : [UIColor whiteColor],
              UITextAttributeTextShadowColor: [UIColor clearColor],
             UITextAttributeTextShadowOffset: [NSValue valueWithUIOffset:UIOffsetMake(0, 0)]
    }];

    return YES;
}
```

**Comment by vuluu** [comment]
The done button is right but the color of title still do not work. If notificationTable is not subclass of UINavigationController do you have any other idea to help me change the color of title ???

**Comment by nicolaschengdev** [comment]
In order to display a title, you have to embed your `NotificationTable` view controller into an `UINavigationController` container controller.

WYPopoverController works like UIPopoverController.

``` objective-c
NotificationTable *notiTable = [[NotificationTable alloc] init];
notiTable.title = @"Notification";

UINavigationController* contentViewController = [[UINavigationController alloc] initWithRootViewController:notiTable];

messagePopover = [[WYPopoverController alloc] initWithContentViewController:contentViewController];
```

In the "WYPopoverDemo" app, the color of title works even if you have a black **fillTopColor**. See screenshot.

I have no idea why your app not works just like demo app.

Step by step try to identify where the issue comes from.

![capture decran du simulateur ios 6 nov 2013 11 27 10](https://f.cloud.github.com/assets/2202583/1481686/8a23ff76-46ce-11e3-927a-07b5934522d0.png)

**Comment by vuluu** [comment]
yes, I got that from beginning so I can not find the logic explanation for that.Maybe my UINavigationController is controlled by JASliderBar. I will retry. Any result thank you million time!!!!

**Comment by vuluu** [comment]
last one problem I want to ask. Now the content of (Pop)contentviewcontroller is a table with many cell, I want to press a cell and the popover is disappear and I go to new viewcontroller. so how can I do it in table did select row???

**Comment by nicolaschengdev** [comment]
There are many ways : Delegation, Notification or Observation.

[When to use Delegation, Notification, or Observation in iOS](http://blog.shinetech.com/2011/06/14/delegation-notification-and-observation/)

That depends of your app.

**Nicolas**

**Comment by vuluu** [comment]
Thank for your helpfull support!! I done!
