### ISSUE TITLE
WYPopoverController is shown 'behind' a UIViewController that is presented modal with 'UIModalPresentationPageSheet'

### ISSUE THREAD

**Issue by SlimShady0208** [nicolaschengdev/WYPopoverController#50]
Hello guys,

I stumbled upon this component 2 days ago and it would fit my requirements perfectly, but I am not getting it running in my scenario.

I built a very simple test case:
- I have a button im my main view, that opens up an UIViewController with 'UIModalPresentationPageSheet' presentation style. 
- Inside this modal view Controller there is another button, which should open up the WYPopoverController. 
- When I touch that button, the WYPopoverController is shown 'behind' the modal view controller.

What am I doing wrong? Is there a bug or did I forget some configuration? Could anyone help me out on this one? I would really like to use this component.

Thanks in advance,
SlimShady0208

**Comment by nicolaschengdev** [comment]
Hi,

can you give it a try again please.

**Nicolas**

**Comment by SlimShady0208** [comment]
Thanks for your work. I did test your fix in my environment. The popover now appears in front of the modal view controller but it is rotated 90° counterclockwise. Could you confirm this behavior?

Regards,
SlimShady0208

**Comment by nicolaschengdev** [comment]
It's not yet perfect. But, for now, with this commit : popovers are not rotated.

**Comment by SlimShady0208** [comment]
Yep ... I can confirm ... the fix is working now. Thanks again.
