### ISSUE TITLE
self.layer.delegate = self; - should the delegate be reset to nil in dealloc for WYPopoverBackgroundView?

### ISSUE THREAD

**Issue by inPhilly** [nicolaschengdev/WYPopoverController#52]
Should you be setting

self.layer.delegate = nil; 

in the dealloc method for WYPopoverBackgroundView? I am having some odd crashes that I cannot reproduce (live apps) and I think I have possibly traced the error back here.

**Comment by inPhilly** [comment]
Does anyone have any thoughts on this? I don't want to change it if changing it will actually cause a problem.

**Comment by nicolaschengdev** [comment]
Hi mommyme,

Did you be able to reproduce crashes ? 

No need to set layer delegate to nil because WYPopoverBackgroundView is properly deallocated from what I see in Instruments.
