### ISSUE TITLE
ios5.0

### ISSUE THREAD

**Issue by avalanched** [nicolaschengdev/WYPopoverController#56]
Why was ios5.1 chosen instead of ios5.0 in the podspec?

on the other hand i get this,

[!] The platform of the target `Pods` (iOS 5.1) is not compatible with `WYPopoverController (0.1.7)` which has a minimum requirement of iOS 6.0.

but the podspec specifies 5.1 as deployment target

**Comment by nicolaschengdev** [comment]
Fixed. Sorry for the late.
