### ISSUE TITLE
rootView some times problem in this place of logic.

### ISSUE THREAD

**Issue by Samback** [nicolaschengdev/WYPopoverController#57]
Probably it will be great not only check for if(!view.isHidden) because when I use hud it's the first element :) Maybe it will be better to check for [view isKindOfClass:UIViewController]  ?
- (UIView *)rootView
  {
  UIWindow *result = [[UIApplication sharedApplication] keyWindow];
  
  if (result.subviews.count > 0)
  {
      for (UIView *view in result.subviews)
      {
          if(!view.isHidden)
          {
              return view;
          }
      }
      // result = [result.subviews lastObject];
  }
  
  return result;
  }

**Comment by hsoi** [comment]
I just got bit by `-rootView` as well, but in a different way.

I looked at the closed issues here and I see #46 and #47 are related, and explain why the `-isHidden` check is in there.

But I'm curious as to why this `-rootView` method is in there in the first place. Why isn't `keyWindow` itself sufficient?  What is `-rootView` trying to accomplish? What assumptions is it making, and could it be stronger and more directly explicit about what it's seeking? @nicolaschengdev you obviously have your reasons for doing what you did and why you did it, and knowing that would be useful in understanding all of this and coming up with a more solid solution (given the current implementation seems to be causing issues for a number of people).

In my case, I am using a debugging tool called [DCIntrospect-ARC](https://github.com/lukaswelte/DCIntrospect-ARC). It inserts a view, `DCTextView` into the window subviews, and it winds up being the view that `-rootView` finds and returns. This of course causes `WYPopoverController` to fail.

I can work around my own special case there (and depending how all this goes, I can submit the workaround in a pull request). But I'd rather see if there's a more solid solution to be had on this issue.

Thanx @nicolaschengdev for both the class itself (so far it seems like the best popover replacement out there these days), and for your consideration on this matter.

**Comment by nicolaschengdev** [comment]
Hi,

a more solid solution is to add popover on top of subviews. In the same window of the view which is passed as argument in the following method : 

``` Objectice-C
- (void)presentPopoverFromRect:(CGRect)rect
                        inView:(UIView *)view
      permittedArrowDirections:(WYPopoverArrowDirection)arrowDirections
                      animated:(BOOL)animated
                       options:(WYPopoverAnimationOptions)options;
```

I am currently working in order to implement this solution. And to support orientation and keyboard with this solution.

**Comment by hsoi** [comment]
Cool. I will look at this in the coming days and let you know how it goes. Thank you!

**Comment by hsoi** [comment]
Finally got a chance to try this out. So far so good! Seems like a better solution all around. Thanx.
