### ISSUE TITLE
WYPopoverController does not conform to UIAppearanceContainer

### ISSUE THREAD

**Issue by boscojwho** [nicolaschengdev/WYPopoverController#59]
WYPopoverController does not conform to UIAppearanceContainer. I'm using pod 'WYPopoverController', '~> 0.1.7' on 7.1 (b3).

Calling something like the following causes crash:
UINavigationBar\* navBarInPopoverAppearance = [UINavigationBar appearanceWhenContainedIn:[UINavigationController class], [WYPopoverController class], nil];

Fix: 
Add protocol to class header: @interface WYPopoverController : NSObject <UIAppearanceContainer>

**Comment by nicolaschengdev** [comment]
Thanks boscojwho !
