### ISSUE TITLE
Navigation bar appearance weird when it is hidden. 

### ISSUE THREAD

**Issue by hubertwang** [nicolaschengdev/WYPopoverController#60]
Hi,

I've started to use WYPopover in my project a few months ago. Everything works fine until I try to put my view controller in a navigation controller.

I need to push another view controller, but I don't need navigation bar in first view controller.
So I set 'top bar' property of the navigation controller to none. However, there is something wrong with the navigation bar.

Here I use the demo project 'DemoSegue' as an example.
Normal
![normal](https://f.cloud.github.com/assets/1281311/1951585/5574fce8-8185-11e3-86d1-9495cbf65a11.png)

Hide Navigation Bar
![abnormal](https://f.cloud.github.com/assets/1281311/1951592/a3acccce-8185-11e3-9415-f4e8deb1da31.png)

It can be seen that there is a weird gray line above the bottom part of 'Player Name'.

Since the background is white, so the problem is not obvious. I changed the background color to make it more obvious.

![abnormal-1](https://f.cloud.github.com/assets/1281311/1951632/acde775a-8187-11e3-9c1e-d4d41fe42926.png)

Is this a bug, or I was using it in a wrong way?

**Comment by nicolaschengdev** [comment]
Hi hubertwang,

it is a bug.
As a workaround, please can you try to define transparent border colors for your popover ?

**Comment by hubertwang** [comment]
Transparent border colors did fix the issue, but I need borders. So I changed top bar property of my first view controller to inferred instead. Anyway, thanks for your workaround :)

**Comment by tranthanhvu** [comment]
@hubertwang, I have the same problem but I don't know how to fix. I don't know What "border color" is. Could you please help me ?

**Comment by hubertwang** [comment]
@tranthanhvu It's inner stroke color. Just set it to clear color, then your problem will be fixed.
    WYPopoverBackgroundView *popoverAppearance = [WYPopoverBackgroundView appearance];
    [popoverAppearance setInnerStrokeColor:[UIColor clearColor]];

**Comment by tranthanhvu** [comment]
@hubertwang :), I got the solution like your. Anyway, thanks for your reply.
