### ISSUE TITLE
When the keyboard over laps the popover

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [nicolaschengdev/WYPopoverController#63]
Hi,

Great library. I'm using this in my second project. In this one however, I have run in to a small situation. The popover I'm displaying is fairly long. Therefore when the keyboard comes up, it overlaps the popover.

As a solution, I added a UIScrollView to the popover and in viewDidLayoutSubviews mthod, I set its its contentSize and frame. Like so

```
self.scrollView.contentSize = CGSizeMake(self.view.frame.size.width, self.scrollView.frame.size.height);
self.scrollView.frame = self.view.frame;
```

This almost works. The scrollview works as expected but there's a small hitch. The scrollview doesn't cover the entire popover screen.
![screen shot 2014-02-02 at 8 30 33 pm](https://f.cloud.github.com/assets/2551877/2060462/d29c2990-8c1a-11e3-9b6b-d1c9af7936de.png)
Notice the first textfield disappearing from the middle of the screen.

I have a demo project here if this is all too confusing.
https://www.dropbox.com/s/gfcp5q364z4k968/PopoverTest.zip

Can you please take a look at it and tell me how to correct this? I'd really appreciate it.

Thank you.

**Comment by viking2009** [comment]
try self.scrollView.frame = self.view.bounds;

**Comment by Isuru-Nanayakkara** [comment]
Works like a charm :+1: Thank you :D

**Comment by nicolaschengdev** [comment]
Thanks!
:+1: for viking2009
