### ISSUE TITLE
Arrow doesn't get the Navigation bar's background color

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [nicolaschengdev/WYPopoverController#67]
My app is a storyboard app and I'm presenting it using WYStoryboardPopoverSegue (like in the DemoSegue project in the example projects). The view controller is embedded in a UINavigationBarController so a a navigation bar appears in the popover view as intended.

Somehow that navigation bar wouldn't conform to the UAppearence proxy I had set up in the app's AppDelegate file. Therefore I changed its background color from in the popover's viewDidLoad method and it works. But the arrow still appears in default color.

![screen shot 2014-02-04 at 10 44 13 am](https://f.cloud.github.com/assets/2551877/2073483/ab7759f4-8d5d-11e3-8baa-dbc6089b61b9.png)

How can I change the arrow's color as well?

I tried making an instance of WYPopoverBackgroundView to set its values and see but I don't know where I should assign the WYPopoverBackgroundView's instance to the popover.

Thank you

**Comment by nicolaschengdev** [comment]
Hi,
you have to change `fillTopColor`and `fillBottomColor`.
Border and arrow colors of the popover come from these two colors.

**Comment by Isuru-Nanayakkara** [comment]
These are properties of WYPopoverBackgroundView, right? Where do I assign the instance of WYPopoverBackgroundView to the WYPopoverController?

**Comment by Isuru-Nanayakkara** [comment]
Got it!  Thank you :+1: 

```
WYPopoverBackgroundView *backgroundView = [WYPopoverBackgroundView appearance];
[backgroundView setFillTopColor:[UIColor GreenColor]];
```
