### ISSUE TITLE
Add animation Option to dismiss

### ISSUE THREAD

**Issue by plaetzchen** [nicolaschengdev/WYPopoverController#69]
Hi,

Thank you for your great work, I really like it!
One issue: If I show the popover I can add an option how it should be animated, unfortunately this is not possible if I dismiss the popover.

Bests,
Philip

**Comment by nicolaschengdev** [comment]
Hi,

now you can add an `option` animation when you dismiss the popoover, with this new method : 

``` Objective-c
- (void)dismissPopoverAnimated:(BOOL)animated options:(WYPopoverAnimationOptions)aOptions;
```

Nicolas
