### ISSUE TITLE
Can't dismiss popover when VoiceOver is turned on

### ISSUE THREAD

**Issue by ghost** [nicolaschengdev/WYPopoverController#70]
Doesn't it work with VoiceOver? If turn on VoiceOver on device and present a popover in app (f.e. in Demo), than tap outside the popover does't dismiss it. The workraround to close popover is to tap "Done" button though.

**Comment by nicolaschengdev** [comment]
VoiceOver speaks items on the screen :
- Tap once to select an item
- Double-Tap to activate the selected item
- Swipe three fingers to scroll

So, double-tap outside of the popover in order to close it when VoiceOver is turned on.

**Comment by Timac** [comment]
There is indeed a problem with VoiceOver. You can't double-tap outside of the popover to close it when VoiceOver is turned on. The issue can be reproduced with the demo app WYPopoverDemo:
- On an iPad turn on VoiceOver
- Launch WYPopoverDemo
- Tap once on 'B' to select it
- Double-Tap on 'B' to open the WYPopover. Note that the title of the view is now selected.
- Double-Tap outside of the popover

Result: The popover is not closed.

**Comment by Timac** [comment]
I just tested and it is indeed fixed now. Thanks!
