### ISSUE TITLE
No way to disable keyboard repositioning

### ISSUE THREAD

**Issue by ogarkov-dev** [nicolaschengdev/WYPopoverController#77]
I have encountered an issue that the popover always adjusts to keyboard offset. Is it possible to add an ability to control this behavior? I need my popover to be visible under iOS 7 keyboard. Some kind of BOOL property would be ideal.

**Comment by nicolaschengdev** [comment]
fixed issue #77, see commit [d7fab2e644...](https://github.com/nicolaschengdev/WYPopoverController/commit/d7fab2e64462ae60ba4392f5290a1effaeabfde4)

By default, when keyboard is shown, popover will be repositionned if it is (partially) hidden.
Introduced in 0.2.1 release, you can control value of y offset when keyboard is shown with the following `delegate` method :

``` objective-c
- (void)popoverController:(WYPopoverController *)popoverController willTranslatePopoverWithYOffset:(CGFloat *)value
{
    *value = 0; // if value is setted to 0 then popover will not be translated
}
```

**Comment by ogarkov-dev** [comment]
Is there a way to completely ignore the keyboard appearance? I mean to avoid even resizing.

**Comment by nicolaschengdev** [comment]
I could add another delegate method : 
`- (BOOL)popoverControllerShouldIgnoreKeyboardBounds:(WYPopoverController *)popoverController`

**Comment by ogarkov-dev** [comment]
That would be great!
Or you can add a BOOL property to your popover instance in order to control this.
