### ISSUE TITLE
New updates 0.2.1 issue

### ISSUE THREAD

**Issue by edward-lay** [nicolaschengdev/WYPopoverController#80]
I replaced with the new updates of 0.2.1 and my current popovers became a blank when I present them. They just show the outline of a square.

I went to see your demo codes and there was almost no changes except for the close method. 

I am currently running ios6 (ios7 also gives me the same problem).

What are the new codes that I need to add?

**Comment by nicolaschengdev** [comment]
Very strange. There are no new codes that you need to add.
Can you send me a sample of your code ?

**Comment by edward-lay** [comment]
sure, I am using these codes below, linked with the storyboard.

```@interface TestViewController () <WYPopoverControllerDelegate> {
    WYPopoverController *checkPopoverController;
}
- (IBAction)showPopover:(UIButton *)button {
  if (checkPopoverController == nil) {
  CheckViewController *checkViewController = [storyboard instantiateViewControllerWithIdentifier:@"CheckViewController"];
  if ([checkViewController respondsToSelector:@selector(setPreferredContentSize:)])
      // iOS 7
      [checkViewController setPreferredContentSize:CGSizeMake(550, 250)];
  else
      // iOS < 7
      [checkViewController setContentSizeForViewInPopover:CGSizeMake(550, 250)];
  [checkViewController setModalInPopover:NO];
  UINavigationController *contentViewController = [[UINavigationController alloc] initWithRootViewController:checkViewController];
  [[checkViewController view] setBackgroundColor:[UIColor redColor]];
  checkPopoverController = [[WYPopoverController alloc] initWithContentViewController:contentViewController];
  [checkPopoverController setDelegate:self];
  [checkPopoverController setPassthroughViews:@[button]];
  [checkPopoverController setPopoverLayoutMargins:UIEdgeInsetsMake(5,5,5,5)];
  [checkPopoverController setWantsDefaultContentAppearance:NO];
  [checkViewController setDelegate:self];
  
  WYPopoverBackgroundView\* popoverAppearance = [WYPopoverBackgroundView appearance];
  [popoverAppearance setFillTopColor:[UIColor grayColor]];
  [popoverAppearance setFillBottomColor:[UIColor grayColor]];
  
  [checkPopoverController presentPopoverFromRect:button.bounds inView:button permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES options:WYPopoverAnimationOptionFadeWithScale];
  } else {
      [self done:nil];
  }
  }
- (void)done:(id)sender {
  [checkPopoverController dismissPopoverAnimated:YES];
  checkPopoverController.delegate = nil;
  checkPopoverController = nil;
  }
- (BOOL)popoverControllerShouldDismissPopover:(WYPopoverController *)controller {
  return YES;
  }
- (void)popoverControllerDidDismissPopover:(WYPopoverController *)controller {
  if (controller == checkPopoverController) {
      checkPopoverController.delegate = nil;
      checkPopoverController = nil;
  }
  }```

**Comment by nicolaschengdev** [comment]
It seems there is nothing wrong with this code.
Are you sure that `checkViewController` reference is not nil ?

**Comment by edward-lay** [comment]
Nope. I did save a previous version of my app (that has ur previous version), there doesn't seem to be much difference when i did those breakpoint and analyse the `checkViewContoller`.

**Comment by nicolaschengdev** [comment]
Demo app works for you ?
I tested it with simulator and device under iOS7. And all tests succeeded.
Did you watch if the size of the view of your view controller is not equal to `CGSizeZero` ?

**Comment by edward-lay** [comment]
Yes demo app works for me. 
I have also tested my app on iOS6 device and it yields the same result.

how do I watch if the size of the view of your view controller is not equal to CGSizeZero ?

**Comment by nicolaschengdev** [comment]
Try this code :

``` Objective-c
@implementation CheckViewController

- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    NSLog(@"view.bounds = %@", NSStringFromCGSize(self.view.bounds));
}

@end
```

**Comment by edward-lay** [comment]
I have tried on 2 apps (one with old WYPOP and the other with new WYPOP lib), and also have used this code instead: 
`NSLog(@"view.bounds = %@", NSStringFromCGRect(self.view.bounds));`

//old version of wypop - view.bounds = {{0, 0}, {552, 211}}
was not able to print any with the new version of lib

any idea?

**Comment by nicolaschengdev** [comment]
There is something wrong with your storyboard if the method `-(void)viewDidAppear:(BOOL)animated` is never called.
Check and check again.

**Comment by ogarkov-dev** [comment]
I have encountered this issue too. It appeared on commit 3fed844d45. Reverting back to  d7fab2e644 (previous one) works nicely.

I am using iOS 7 only and this code for appearance:

``` Objective-C
    _popoverViewController = [[WYPopoverController alloc] initWithContentViewController:controller];
    _popoverViewController.popoverLayoutMargins = UIEdgeInsetsMake(0.0, 0.0, 0.0, 0.0);
    _popoverViewController.delegate = self;
    _popoverViewController.animationDuration = animationDuration;

    [_popoverViewController presentPopoverFromRect:[(UIButton*)view frame] inView:self.view permittedArrowDirections:WYPopoverArrowDirectionUp animated:YES options:WYPopoverAnimationOptionFade];
```

**Comment by ogarkov-dev** [comment]
That is interesting. This code works as needed even on 3fed844 commit:

``` Objective-C
    self.popoverViewController = [[WYPopoverController alloc] initWithContentViewController:controller];
    self.popoverViewController.popoverContentSize = controller.view.frame.size;
    self.popoverViewController.popoverLayoutMargins = UIEdgeInsetsMake(0, 170, 105, 0);
    self.popoverViewController.delegate = self;

    WYPopoverTheme *newTheme = [WYPopoverTheme themeForIOS7];

    newTheme.outerCornerRadius = 2;
    newTheme.outerShadowBlurRadius = 3;
    newTheme.outerShadowColor = [UIColor colorWithWhite:0.000 alpha:0.500];
    newTheme.overlayColor = [UIColor colorWithWhite:0.000 alpha:0.330];

    self.popoverViewController.theme = newTheme;
    [self.popoverViewController presentPopoverFromRect:CGRectMake(self.view.frame.size.width, 0, 1, 1)
                                                inView:self.view
                              permittedArrowDirections:WYPopoverArrowDirectionNone
                                              animated:YES
                                               options:WYPopoverAnimationOptionFade];
```

**Comment by edward-lay** [comment]
@anToha could you reset your simulator or delete the app on your device and try again, see if it works?

**Comment by ogarkov-dev** [comment]
@edward-lay that did not help. My first code snippet works as described but the second one works perfectly.

**Comment by edward-lay** [comment]
okay, I figured this out. the new necessary code to add with the new update 0.2.1 is the setting the theme regardless of whether the platform is iOS6/iOS7

WYPopoverTheme *newTheme = [WYPopoverTheme themeForIOS6];
anyPopoverController.theme = newTheme;

(and yes in this way, the `-(void)viewDidAppear:(BOOL)animated` will be called)

**Comment by ogarkov-dev** [comment]
Yes, that fixed my issue.

So the problem is that the default theme is not automatically initialized.

Here is the code snippet (WYPopoverController.m:1627) describing the bug:

``` Objective-C
+ (WYPopoverTheme *)defaultTheme
{
    return defaultTheme_;
}

+ (void)initialize
{
    [WYPopoverController setDefaultTheme:[WYPopoverController defaultTheme]];
}
```

It is initialized with itself here.
But if there is no default theme iOS6 / iOS7 theme should be used.

**Comment by nicolaschengdev** [comment]
Thanks to you both !
I think issue is resolved now.

**Comment by ogarkov-dev** [comment]
Now works perfectly!
@nicolaschengdev thank you for a great project and instant support!

**Comment by edward-lay** [comment]
thanks for the library too~ (=
