### ISSUE TITLE
Not working correctly with 64-bit apps

### ISSUE THREAD

**Issue by gilroykilroy** [nicolaschengdev/WYPopoverController#81]
Everything works fine under the simulator but not on an actual iPad Air. I traced it down to the appearance local in the init method. It seems it is not returning good values on the device (items like arrowBase and arrowHeight are 0).

The appearance proxy stuff isn't working.

**Comment by nicolaschengdev** [comment]
Hi, could you give it a try again.

**Comment by gilroykilroy** [comment]
I can’t seem to get the latest version. cocoa pods still gets 0.2.2. Tried using the git option and that still doesn’t fix the issue.

**Comment by gilroykilroy** [comment]
I cloned the repo directly and see you updated the demo only. I am using WYPopoverController directly without making any appearance changes in my app.

**Comment by gilroykilroy** [comment]
I see the change from initialize to load now. However that didn’t fix the issue either.

**Comment by nicolaschengdev** [comment]
Did you look the demo app ?

Here my code how to customize my popover with UIAppearance proxy : 

``` Objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    ...
    WYPopoverBackgroundView *popoverAppearance = [WYPopoverBackgroundView appearance];
    [popoverAppearance setArrowHeight:70];
    [popoverAppearance setArrowBase:30];
    ...
    return YES;
}
```

**Comment by gilroykilroy** [comment]
But I am not customizing the appearance in any way, I use it out of the box. Somehow the appearance proxy stuff isn't working right on a device.

**Comment by nicolaschengdev** [comment]
My code was tested on an iPad Air under iOS 7.0.4 with the code below : 

``` Objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    ...
    WYPopoverBackgroundView *popoverAppearance = [WYPopoverBackgroundView appearance];
    [popoverAppearance setArrowHeight:70];
    [popoverAppearance setArrowBase:30];
    ...
    return YES;
}
```

UIAppearance proxy is working like expected.

What is your code ?

**Comment by gilroykilroy** [comment]
I'm trying to figure out why your demo works fine but my app doesn't.

**Comment by nicolaschengdev** [comment]
Ok, thanks. It will be more easy for me to help you if you can find location of issue.

**Comment by gilroykilroy** [comment]
I added this to setDefaultTheme:

```
    appearance.arrowHeight = aTheme.arrowHeight;
NSLog(@"appearance %@ arrowHeight %f, aTheme %@ arrowHeight %f", appearance, appearance.arrowHeight, aTheme, aTheme.arrowHeight);
```

and on my sim it logs

2014-02-23 08:00:28.335 WP[7168:70b] appearance <_UIAppearance:0x9b2d840> <Customizable class: WYPopoverBackgroundView> with invocations (...
 )> arrowHeight 13.000000, aTheme <WYPopoverTheme: 0x9b2aa30> arrowHeight 13.000000

but on my device it logs

2014-02-23 08:01:03.775 WP[6180:60b] appearance <_UIAppearance:0x170240690> <Customizable class: WYPopoverBackgroundView> with invocations (...
 )> arrowHeight 0.000000, aTheme <WYPopoverTheme: 0x1701dbb70> arrowHeight 13.000000

whereas in your demo on the device it logs

2014-02-23 08:01:49.666 WYPopoverDemo[6190:60b] appearance <_UIAppearance:0x16534c40> <Customizable class: WYPopoverBackgroundView> with invocations (...
 )> arrowHeight 13.000000, aTheme <WYPopoverTheme: 0x16531710> arrowHeight 13.000000

So something funky is going on with [WYPopoverBackgroundView appearance] in my app on my device.

**Comment by gilroykilroy** [comment]
I figured it out (but don't understand why): If you include the 64-bit architecture in the build (which my app did but your demo didn't) then they both fail. Removing the 64-bit build makes it work.

**Comment by gilroykilroy** [comment]
Submitted bug 16143704 : CGFloat in Appearance proxy not working in 64-bit architecture

**Comment by nicolaschengdev** [comment]
And what happens if we use float instead of CGFloat ?

**Comment by gilroykilroy** [comment]
That did not work either. Changing them to NSIntegers did work.

**Comment by nicolaschengdev** [comment]
I have changed them to `NSUInteger`.
