### ISSUE TITLE
UINavigationBar appearance

### ISSUE THREAD

**Issue by ericertl** [nicolaschengdev/WYPopoverController#83]
The navigation bar in the popover doesn't apply the settings from UIAppearance set in the appdelegate.
[[UINavigationBar appearance] setBarTintColor:....
[[UINavigationBar appearance] setTintColor:....

Do you know what could be causing this?

Here's a screenshot of how the app nav bar looks like and the popover nav bar:
![image](https://f.cloud.github.com/assets/777783/2262184/1196687e-9e57-11e3-907b-abe0ce164f21.png)

**Comment by nicolaschengdev** [comment]
An exemple for iOS7 :

``` Objective-c
UINavigationBar *navBarInPopoverAppearance = [UINavigationBar appearanceWhenContainedIn:[UINavigationController class], [WYPopoverBackgroundView class], nil];

NSShadow *shadow = [[NSShadow alloc] init];
[shadow setShadowColor:[UIColor clearColor]];
[shadow setShadowOffset:CGSizeZero];

[navBarInPopoverAppearance setTitleTextAttributes:
    @{
            NSForegroundColorAttributeName : [UIColor purpleColor],
            NSShadowAttributeName: shadow
    }];
```
