### ISSUE TITLE
UIAppearance-based configuration seems broken

### ISSUE THREAD

**Issue by tschmitz** [nicolaschengdev/WYPopoverController#84]
I recently tried to configure popover appearance using the UIAppearance selectors and was unable to get them to work. For instance, I tried one of the examples given in the readme:

```
WYPopoverBackgroundView* appearance = [WYPopoverBackgroundView appearance];
[appearance setTintColor:[UIColor orangeColor]];
```

This seemed to have no effect. However, the theme-based approach did work:

```
WYPopoverTheme *theme = [WYPopoverTheme themeForIOS7];
theme.tintColor = [UIColor orangeColor];
[WYPopoverController setDefaultTheme:theme];
```

**Comment by tschmitz** [comment]
Quick update: It looks like setting the default to a generic theme allows the UIAppearance selectors to work:

```
[WYPopoverController setDefaultTheme:[WYPopoverTheme theme]];
[[WYPopoverBackgroundView appearance] setBorderWidth:10];
[[WYPopoverBackgroundView appearance] setFillTopColor:[UIColor redColor]];
```

Perhaps it'd be worth adding that to the documentation?

**Comment by nicolaschengdev** [comment]
Thank you @tschmitz 
I have updated README file.

Next release of `WYPopoverController` will initialize automatically a default theme for you.
