### ISSUE TITLE
Animation not shown when dismissing manually

### ISSUE THREAD

**Issue by Ricardo1980** [nicolaschengdev/WYPopoverController#87]
Hello! Thanks for your component, very useful ;)

One problem I have, my popover has 2 buttons, DONE and CANCEL. I created a custom delegate, that dismisses the popover when one of those 2 buttons are pressed., something like:
- (void) cancelledCategorySelection
  {
  [_categoriesPopoverController dismissPopoverAnimated:YES];
  self.categoriesPopoverController=nil;
  }

Problem is that I don't see the animation when is dismissed. However if I remove the second line,  self.categoriesPopoverController=nil; then I see the animation, but in that case I have that variable that contains the popover which is not needed anymore.

Any idea or suggestion?
Thanks in advance.

**Comment by nicolaschengdev** [comment]
Hi,

 try this : 

``` Objective-c
- (void) cancelledCategorySelection { 
    [_categoriesPopoverController dismissPopoverAnimated:YES];
    //self.categoriesPopoverController=nil;  // popover is deallocated and all animations are removed
}
```

Or use this : 

``` Objective-c
- (void) cancelledCategorySelection { 
    [_categoriesPopoverController dismissPopoverAnimated:YES completion:^{
        self.categoriesPopoverController=nil;
    }];
}
```

**Comment by Ricardo1980** [comment]
Thanks!
The first one has the problem that you are wasting memory.
The second one,I see a potential problem, which is tapping too fast an showing one popover after another. Then when the first is being closed, it could release the variable that is used by the first one, isn't it?
Thanks.

**Comment by nicolaschengdev** [comment]
In the first, I have to think about.

In the second, if you create another popover then the first is deallocated. 

Nicolas
