### ISSUE TITLE
Present WYPopoverController constrained in view

### ISSUE THREAD

**Issue by VrasidasP** [nicolaschengdev/WYPopoverController#97]
In iPad, I want to present a WYPopoverController from a button which is inside a container subview of my main view.

I present it using:
[popoverController presentPopoverFromRect:sender.bounds inView:sender permittedArrowDirections:WYPopoverArrowDirectionAny animated:YES options:WYPopoverAnimationOptionScale];

I want the popover to stay confined inside the subview. 
I've tried setting the popoverLayoutMargins according to the container subview frame but it doesn't work as I thought it would.

This is what I get, I want the popover to be completely inside the gray area on the left.
http://i.imgur.com/C74bVOb.png

Any help is appreciated. Thanks!

**Comment by VrasidasP** [comment]
Never mind, it was actually the popoverLayoutMargins, I just wasn't passing correct values. :)

**Comment by mohpor** [comment]
I still can't get the desired value. In my case I want my popover's width to be fitted inside another view I tried everything I know and it still has a little offset in the right.
This layout margin doesn't work either. 
Gotta admit, I have a complex view hierarchy and my Popover should be presented from 3rd layer of container views, but I hope there's still a chance to do it.
Can anyone help on this?
